
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 08 22:23:53 CST 2019
//----------------------------------------------------

package backend.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Nombre = 15;
  public static final int Entero = 55;
  public static final int Padre = 53;
  public static final int ModificarPagina = 49;
  public static final int BorrarPagina = 44;
  public static final int Id = 4;
  public static final int Derecha = 22;
  public static final int Atributo = 13;
  public static final int VideoComponente = 56;
  public static final int TextColor = 5;
  public static final int Clase = 54;
  public static final int Izquierda = 39;
  public static final int ModificarComponente = 38;
  public static final int UsuarioCreacion = 35;
  public static final int TituloComponente = 11;
  public static final int Etiquetas = 27;
  public static final int ImagenComponente = 33;
  public static final int BorrarSitioWeb = 42;
  public static final int Titulo = 50;
  public static final int Color = 10;
  public static final int MenuComponente = 47;
  public static final int UsuarioModificacion = 41;
  public static final int Valor = 28;
  public static final int Acciones = 12;
  public static final int BorrarComponente = 45;
  public static final int Etiqueta = 3;
  public static final int Diagonal = 25;
  public static final int EOF = 0;
  public static final int Sitio = 52;
  public static final int MayorQue = 26;
  public static final int error = 1;
  public static final int Accion = 6;
  public static final int Texto = 8;
  public static final int ErrorLexico = 57;
  public static final int Justificar = 46;
  public static final int Atributos = 14;
  public static final int ParrafoComponente = 24;
  public static final int URL = 19;
  public static final int Origen = 21;
  public static final int AtributoEtiquetas = 32;
  public static final int Alineacion = 40;
  public static final int Parametros = 30;
  public static final int DatoEntreComillas = 7;
  public static final int Centrar = 23;
  public static final int NuevaPagina = 43;
  public static final int Identificador = 2;
  public static final int Ancho = 9;
  public static final int Altura = 20;
  public static final int MenorQue = 17;
  public static final int Parametro = 29;
  public static final int AgregarComponente = 48;
  public static final int FechaCreacion = 36;
  public static final int Fecha = 18;
  public static final int ValorParametro = 31;
  public static final int Pagina = 51;
  public static final int Igual = 16;
  public static final int FechaModificacion = 37;
  public static final int NuevoSitioWeb = 34;
}

