
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 07 22:08:28 CST 2019
//----------------------------------------------------

package backend.analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosUsuarios {
  /* terminals */
  public static final int MayorQue = 8;
  public static final int Usuarios = 3;
  public static final int Contraseña = 5;
  public static final int Id = 4;
  public static final int Usuario = 2;
  public static final int DatoEntreComillas = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Igual = 6;
  public static final int MenorQue = 7;
  public static final int Diagonal = 9;
}

